/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function HeroCharacters(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "models/Hero-V2-proc-meshopt-m.glb"
  );
const { actions } = useAnimations(animations, group);

useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        if (action && action.play) {
          action.play();
        }
      });
    }
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Hero_V2glb">
          <primitive object={nodes.Ch2b_CTRL22} />
          <primitive object={nodes.Ch4_CTRL36} />
          <primitive object={nodes.Ch5_CTRL63} />
          <primitive object={nodes.Ch03e_CTRL84} />
          <group
            name="Cutlery019"
            position={[0.169, 0.809, -3.859]}
            rotation={[0, -1.57, 0]}
          >
            <mesh
              name="Cutlery035"
              castShadow
              receiveShadow
              geometry={nodes.Cutlery035.geometry}
              material={nodes.Cutlery035.material}
              position={[-0.124, 0, -0.231]}
              rotation={[0, -0.028, 0]}
              scale={0.55}
            />
          </group>
          <group
            name="Cutlery024"
            position={[0.619, 0.809, -3.859]}
            rotation={[0, -1.57, 0]}
          />
          <group
            name="Cutlery029"
            position={[0.619, 0.809, -4.513]}
            rotation={[0, -1.57, 0]}
          />
          <group name="Point269" position={[0, 1.672, -5.34]} />
          <mesh
            name="Cylinder001"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={nodes.Cylinder001.material}
            position={[0.4, 0.811, -3.979]}
            scale={0.465}
          />
          <skinnedMesh
            name="Ch5_Mesh04"
            geometry={nodes.Ch5_Mesh04.geometry}
            material={nodes.Ch5_Mesh04.material}
            skeleton={nodes.Ch5_Mesh04.skeleton}
            position={[0, -0.004, -0.03]}
            scale={1.358}
          />
          <skinnedMesh
            name="minahead004www"
            geometry={nodes.minahead004www.geometry}
            material={nodes.minahead004www.material}
            skeleton={nodes.minahead004www.skeleton}
            position={[0, 1.448, -0.016]}
            scale={0.904}
          />
          <skinnedMesh
            name="minahead004wweweedewed"
            geometry={nodes.minahead004wweweedewed.geometry}
            material={nodes.minahead004wweweedewed.material}
            skeleton={nodes.minahead004wweweedewed.skeleton}
            position={[0, 1.562, -0.03]}
            scale={1.058}
          />
          <skinnedMesh
            name="minahead004fffe"
            geometry={nodes.minahead004fffe.geometry}
            material={nodes.minahead004fffe.material}
            skeleton={nodes.minahead004fffe.skeleton}
            position={[0, 1.456, -0.009]}
          />
          <skinnedMesh
            name="Object102"
            geometry={nodes.Object102.geometry}
            material={nodes.Object102.material}
            skeleton={nodes.Object102.skeleton}
            position={[0, 1.328, 0.006]}
            scale={1.058}
          />
          <skinnedMesh
            name="Ch4_Mesh07"
            geometry={nodes.Ch4_Mesh07.geometry}
            material={nodes.Ch4_Mesh07.material}
            skeleton={nodes.Ch4_Mesh07.skeleton}
            position={[0, 1.328, 0.006]}
            scale={1.058}
          />
          <skinnedMesh
            name="Ch5_Mesh07"
            geometry={nodes.Ch5_Mesh07.geometry}
            material={nodes.Ch5_Mesh07.material}
            skeleton={nodes.Ch5_Mesh07.skeleton}
            position={[0, 1.224, 0.022]}
          />
          <skinnedMesh
            name="Ch4_Mesh010"
            geometry={nodes.Ch4_Mesh010.geometry}
            material={nodes.Ch4_Mesh010.material}
            skeleton={nodes.Ch4_Mesh010.skeleton}
            position={[0, 1.215, 0.032]}
            scale={1.058}
          />
          <skinnedMesh
            name="Ch03e_Mesh00"
            geometry={nodes.Ch03e_Mesh00.geometry}
            material={nodes.Ch03e_Mesh00.material}
            skeleton={nodes.Ch03e_Mesh00.skeleton}
          />
          <skinnedMesh
            name="Ch03e_Mesh01"
            geometry={nodes.Ch03e_Mesh01.geometry}
            material={nodes.Ch03e_Mesh01.material}
            skeleton={nodes.Ch03e_Mesh01.skeleton}
          />
          <skinnedMesh
            name="Ch03e_Mesh02"
            geometry={nodes.Ch03e_Mesh02.geometry}
            material={nodes.Ch03e_Mesh02.material}
            skeleton={nodes.Ch03e_Mesh02.skeleton}
            position={[0, 1.505, 0.006]}
            scale={[0.494, 0.541, 0.494]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/Hero-V2-proc-meshopt-m.glb");
