/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function HeroModel(props) {
  const { nodes, materials } = useGLTF("models/newHeroFloorless.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_008.geometry}
        material={nodes.walls_008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_010.geometry}
        material={materials.diagonal_parquet}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_001.geometry}
        material={nodes.walls_001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_002.geometry}
        material={nodes.walls_002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_003.geometry}
        material={nodes.walls_003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_004.geometry}
        material={nodes.walls_004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_005.geometry}
        material={nodes.walls_005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_007.geometry}
        material={nodes.walls_007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_009.geometry}
        material={nodes.walls_009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_011.geometry}
        material={nodes.walls_011.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_014.geometry}
        material={nodes.walls_014.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_015.geometry}
        material={nodes.walls_015.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_016.geometry}
        material={nodes.walls_016.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items007.geometry}
        material={materials["Material.008"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items014.geometry}
        material={materials.plywood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items015.geometry}
        material={materials["Material.010"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items017.geometry}
        material={nodes.items017.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items019.geometry}
        material={materials["Material.009"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items020.geometry}
        material={materials.plywood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items021.geometry}
        material={materials.sofas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items024.geometry}
        material={nodes.items024.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items025.geometry}
        material={nodes.items025.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items012.geometry}
        material={materials["Material.006"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items030.geometry}
        material={materials.chairs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items033.geometry}
        material={materials.chairs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items036.geometry}
        material={nodes.items036.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items039.geometry}
        material={materials["Material.008"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items042.geometry}
        material={materials["Material.011"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items057.geometry}
        material={nodes.items057.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items058.geometry}
        material={nodes.items058.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items062.geometry}
        material={materials["Material.007"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items065.geometry}
        material={nodes.items065.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items001.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items060.geometry}
        material={nodes.items060.material}
        position={[0.161, -0.012, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items043.geometry}
        material={materials["Material.012"]}
        position={[0.132, 0, -0.554]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items047.geometry}
        material={nodes.items047.material}
        position={[0.132, 0, -0.554]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items044.geometry}
        material={nodes.items044.material}
        position={[-0.45, 0, -0.441]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items048.geometry}
        material={nodes.items048.material}
        position={[-0.45, 0, -0.441]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items049.geometry}
        material={nodes.items049.material}
        position={[-0.459, 0, 0.175]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items050.geometry}
        material={nodes.items050.material}
        position={[-0.317, 0, 0.783]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items023.geometry}
        material={nodes.items023.material}
        position={[2.476, 0.045, -5.532]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items066.geometry}
        material={materials.chairs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items034.geometry}
        material={nodes.items034.material}
        position={[2.129, 0.19, -5.209]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items051.geometry}
        material={nodes.items051.material}
        position={[2.467, 0.637, -4.311]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items035.geometry}
        material={nodes.items035.material}
        position={[2.762, 1.159, -4.538]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items038.geometry}
        material={nodes.items038.material}
        position={[-2.682, 0.546, -5.287]}
        rotation={[-Math.PI, 1.363, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items005.geometry}
        material={nodes.items005.material}
        position={[-4.033, 0.546, -5.224]}
        rotation={[-Math.PI, 0.472, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items059.geometry}
        material={nodes.items059.material}
        position={[2.73, 1.059, -2.423]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items029.geometry}
        material={nodes.items029.material}
        position={[-1.431, 2.296, -6.323]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items054.geometry}
        material={nodes.items054.material}
        position={[-1.951, 0.079, -5.759]}
        rotation={[-Math.PI / 2, 0, -0.741]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items008.geometry}
        material={materials["Material.003"]}
        position={[-3.908, 0.399, 2.182]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items027.geometry}
        material={materials["Material.014"]}
        position={[-4.579, 2.331, -6.249]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items028.geometry}
        material={materials["Material.014"]}
        position={[-1.546, 2.331, -6.249]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items009.geometry}
        material={materials["Material.004"]}
        position={[-3.908, 0.399, 2.182]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items004.geometry}
        material={nodes.items004.material}
        position={[-4.033, 0.546, -5.224]}
        rotation={[-Math.PI, 0.472, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items006.geometry}
        material={nodes.items006.material}
        position={[-4.033, 0.546, -5.224]}
        rotation={[-Math.PI, 0.472, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items002.geometry}
        material={nodes.items002.material}
        position={[-2.682, 0.546, -5.287]}
        rotation={[-Math.PI, 1.363, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items003.geometry}
        material={nodes.items003.material}
        position={[-2.682, 0.546, -5.287]}
        rotation={[-Math.PI, 1.363, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items022.geometry}
        material={nodes.items022.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items031.geometry}
        material={materials.sofas}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items032.geometry}
        material={materials.sofas}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items064.geometry}
        material={nodes.items064.material}
        position={[-4.918, 0.041, -5.943]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items061.geometry}
        material={materials["Material.007"]}
        position={[0.161, -0.012, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items052.geometry}
        material={nodes.items052.material}
        position={[-1.91, 0.043, -5.67]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items053.geometry}
        material={nodes.items053.material}
        position={[-1.91, 0.043, -5.67]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items055.geometry}
        material={nodes.items055.material}
        position={[-1.91, 0.043, -5.67]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items056.geometry}
        material={nodes.items056.material}
        position={[-1.91, 0.043, -5.67]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items063.geometry}
        material={materials["Material.013"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items010.geometry}
        material={materials["Material.003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items026.geometry}
        material={nodes.items026.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/newHeroFloorless.glb");
