/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SecondModel(props) {
  const { nodes, materials } = useGLTF("models/newsecondmodelfarhan.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls003.geometry}
        material={materials.laminate_floor}
        position={[-1.488, -0.033, -0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls007.geometry}
        material={materials.slab_tiles}
        position={[-2.879, 0.445, -0.957]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls006.geometry}
        material={materials.slab_tiles}
        position={[0.138, -0.446, -1.991]}
        rotation={[0.25, -0.003, -1.581]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls002.geometry}
        material={materials["Material.012"]}
        position={[1.49, -0.168, -0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls004.geometry}
        material={nodes.walls004.material}
        position={[-1.501, -0.168, -0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls005.geometry}
        material={materials.slab_tiles}
        position={[0.573, 1.1, 0.789]}
        rotation={[Math.PI / 2, 1.269, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items004.geometry}
        material={materials["Material.002"]}
        position={[-0.592, -0.026, -1.58]}
        rotation={[-Math.PI, 1.4, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items006.geometry}
        material={materials["Material.005"]}
        position={[-1.524, 0.268, -0.882]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items007.geometry}
        material={materials["Material.007"]}
        position={[-1.524, 0.152, -0.882]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items013.geometry}
        material={nodes.items013.material}
        position={[-1.517, 0.74, -2.336]}
        rotation={[-Math.PI / 2, 0, 0.475]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items003.geometry}
        material={materials["Material.003"]}
        position={[-1.558, 0.326, -2.406]}
        rotation={[-Math.PI / 2, 0, 0.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items001.geometry}
        material={materials["Material.011"]}
        position={[-1.512, 0.74, -2.326]}
        rotation={[-Math.PI / 2, 0, 0.475]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items019.geometry}
        material={materials["Material.003"]}
        position={[1.428, 0.313, 0.69]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items018.geometry}
        material={nodes.items018.material}
        position={[1.428, 0.629, 0.69]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items024.geometry}
        material={materials.slab_tiles}
        position={[-2.067, 0.009, -2.709]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items025.geometry}
        material={materials.slab_tiles}
        position={[2.709, 0.133, -2.747]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items023.geometry}
        material={nodes.items023.material}
        position={[1.639, 0.64, 0.453]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items026.geometry}
        material={nodes.items026.material}
        position={[1.6, 0.638, 0.785]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items012.geometry}
        material={nodes.items012.material}
        position={[2.29, 0.006, -1.669]}
        rotation={[Math.PI, -0.144, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items009.geometry}
        material={nodes.items009.material}
        position={[-2.263, 0.11, -0.788]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items011.geometry}
        material={nodes.items011.material}
        position={[-1.682, 0.071, 0.826]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items002.geometry}
        material={materials["Material.010"]}
        position={[1.414, -0.061, -2.432]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items020.geometry}
        material={materials["Material.009"]}
        position={[1.414, 0.704, -2.447]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items005.geometry}
        material={materials["Material.008"]}
        position={[2.17, 0.61, 0.303]}
        rotation={[0, -0.341, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items021.geometry}
        material={nodes.items021.material}
        position={[1.458, 0.718, -2.4]}
        rotation={[1.583, 0.073, 0.043]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items008.geometry}
        material={materials["Material.001"]}
        position={[-2.521, 0.417, -0.777]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items010.geometry}
        material={materials["Material.006"]}
        position={[-1.678, 0.398, 0.845]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items015.geometry}
        material={materials["Material.004"]}
        position={[-2.358, -0.024, -2.698]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items016.geometry}
        material={nodes.items016.material}
        position={[1.513, 0.598, 0.45]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items022.geometry}
        material={nodes.items022.material}
        position={[1.535, 0.602, 0.683]}
        rotation={[-Math.PI / 2, 0, -0.974]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ficus_4_obj.geometry}
        material={materials["Material.004"]}
        position={[2.725, -0.516, -2.726]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items027.geometry}
        material={materials["Material.008"]}
        position={[2.276, 0.61, 0.446]}
        rotation={[0, -0.341, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items029.geometry}
        material={nodes.items029.material}
        position={[2.396, 0.006, -1.526]}
        rotation={[Math.PI, -0.144, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items030.geometry}
        material={materials["Material.008"]}
        position={[0.736, 0.61, 1.07]}
        rotation={[0, -0.341, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items031.geometry}
        material={materials["Material.003"]}
        position={[0.733, 0.227, 1.068]}
        rotation={[Math.PI / 2, 0, 1.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items032.geometry}
        material={nodes.items032.material}
        position={[0.733, 0.006, 1.068]}
        rotation={[Math.PI, -0.144, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ficus_4_obj001.geometry}
        material={nodes.Ficus_4_obj001.material}
        position={[2.725, -0.516, -2.726]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.002}
      />
    </group>
  );
}

useGLTF.preload("models/newsecondmodelfarhan.glb");
