/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function SecondCharacters(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "models/ListedEverywhere-proc-meshopt-m.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        if (action && action.play) {
          action.play();
        }
      });
    }
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ListedEverywhereglb">
          <primitive object={nodes.NGon125} />
          <primitive object={nodes.Ch1_CTRL00} />
          <primitive object={nodes.Ch2b_CTRL22} />
          <primitive object={nodes.Ch4_CTRL36} />
          <group name="Point194" position={[0, 1.017, 0.002]} />
          <mesh
            name="Object102"
            castShadow
            receiveShadow
            geometry={nodes.Object102.geometry}
            material={nodes.Object102.material}
            position={[0.71, 0.794, 1.048]}
            scale={0.173}
          />
          <skinnedMesh
            name="Box134"
            geometry={nodes.Box134.geometry}
            material={nodes.Box134.material}
            skeleton={nodes.Box134.skeleton}
          />
          <skinnedMesh
            name="Ch2_Mesh49"
            geometry={nodes.Ch2_Mesh49.geometry}
            material={nodes.Ch2_Mesh49.material}
            skeleton={nodes.Ch2_Mesh49.skeleton}
            position={[0, -0.004, -0.03]}
            scale={1.358}
          />
          <skinnedMesh
            name="Object072"
            geometry={nodes.Object072.geometry}
            material={nodes.Object072.material}
            skeleton={nodes.Object072.skeleton}
          />
          <skinnedMesh
            name="Box142"
            geometry={nodes.Box142.geometry}
            material={nodes.Box142.material}
            skeleton={nodes.Box142.skeleton}
            position={[0, 1.505, 0.006]}
            scale={[0.494, 0.541, 0.494]}
          />
          <skinnedMesh
            name="Ch1_Mesh21"
            geometry={nodes.Ch1_Mesh21.geometry}
            material={nodes.Ch1_Mesh21.material}
            skeleton={nodes.Ch1_Mesh21.skeleton}
            position={[0, 1.497, 0.042]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.151}
          />
          <skinnedMesh
            name="Ch2_Mesh69"
            geometry={nodes.Ch2_Mesh69.geometry}
            material={nodes.Ch2_Mesh69.material}
            skeleton={nodes.Ch2_Mesh69.skeleton}
            position={[0, 1.224, 0.022]}
          />
          <skinnedMesh
            name="minahead004www"
            geometry={nodes.minahead004www.geometry}
            material={nodes.minahead004www.material}
            skeleton={nodes.minahead004www.skeleton}
            position={[0, 1.448, -0.016]}
            scale={0.904}
          />
          <skinnedMesh
            name="minahead004wweweedewed"
            geometry={nodes.minahead004wweweedewed.geometry}
            material={nodes.minahead004wweweedewed.material}
            skeleton={nodes.minahead004wweweedewed.skeleton}
            position={[0, 1.562, -0.03]}
            scale={1.058}
          />
          <skinnedMesh
            name="Ch4_Mesh07"
            geometry={nodes.Ch4_Mesh07.geometry}
            material={nodes.Ch4_Mesh07.material}
            skeleton={nodes.Ch4_Mesh07.skeleton}
            position={[0, 1.328, 0.006]}
            scale={1.058}
          />
          <skinnedMesh
            name="Object154"
            geometry={nodes.Object154.geometry}
            material={nodes.Object154.material}
            skeleton={nodes.Object154.skeleton}
            position={[0, 1.227, 0.021]}
          />
          <skinnedMesh
            name="Object155"
            geometry={nodes.Object155.geometry}
            material={nodes.Object155.material}
            skeleton={nodes.Object155.skeleton}
            position={[0, 1.227, 0.021]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/ListedEverywhere-proc-meshopt-m.glb");
