/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export  function ThirdModelFix(props) {
  const { nodes, materials } = useGLTF("models/newfixedmodel.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall001.geometry}
        material={nodes.wall001.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall002.geometry}
        material={nodes.wall002.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall003.geometry}
        material={nodes.wall003.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall004.geometry}
        material={nodes.wall004.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall006.geometry}
        material={nodes.wall006.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall007.geometry}
        material={materials.slab_tiles}
        position={[0.335, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall008.geometry}
        material={nodes.wall008.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall009.geometry}
        material={nodes.wall009.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall010.geometry}
        material={nodes.wall010.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall011.geometry}
        material={nodes.wall011.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall012.geometry}
        material={nodes.wall012.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall014.geometry}
        material={nodes.wall014.material}
        position={[1.087, 1.41, -3.626]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall021.geometry}
        material={nodes.wall021.material}
        position={[-0.28, -0.692, 0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall027.geometry}
        material={nodes.wall027.material}
        position={[1.551, -1.135, -0.936]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall036.geometry}
        material={nodes.wall036.material}
        position={[3.213, -0.483, -1.259]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall037.geometry}
        material={nodes.wall037.material}
        position={[3.213, -0.483, -1.865]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall045.geometry}
        material={materials.rusty_metal_02}
        position={[1.552, -0.48, 0.601]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items081.geometry}
        material={materials["Material.016"]}
        position={[2.668, 0.004, -3.298]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items091.geometry}
        material={nodes.items091.material}
        position={[1.072, 0.889, -3.334]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items056.geometry}
        material={nodes.items056.material}
        position={[-0.677, 0, -0.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items070.geometry}
        material={nodes.items070.material}
        position={[-1.449, 0.001, -0.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items002.geometry}
        material={materials["Material.001"]}
        position={[-2.351, 0.27, 0.311]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items003.geometry}
        material={nodes.items003.material}
        position={[-2.562, 0, 1.266]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items004.geometry}
        material={nodes.items004.material}
        position={[-2.635, 1.298, 1.657]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items005.geometry}
        material={nodes.items005.material}
        position={[-2.476, 1.298, 1.657]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items007.geometry}
        material={materials["Material.005"]}
        position={[-2.56, 0.724, 0.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items050.geometry}
        material={materials["Material.015"]}
        position={[-2.696, 0.841, 0.322]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items074.geometry}
        material={nodes.items074.material}
        position={[-2.507, 0.726, 0.322]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items075.geometry}
        material={materials.wood_table_worn}
        position={[-2.56, 0, 1.266]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items082.geometry}
        material={nodes.items082.material}
        position={[-2.361, 0.669, 0.321]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items083.geometry}
        material={materials.wood_table_worn}
        position={[-2.801, 1.423, 1.145]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items072.geometry}
        material={nodes.items072.material}
        position={[-0.534, 0.966, -3.383]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items073.geometry}
        material={nodes.items073.material}
        position={[-0.577, 0.838, -3.471]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items001.geometry}
        material={materials["Material.012"]}
        position={[-0.522, 1.096, -3.436]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items012.geometry}
        material={nodes.items012.material}
        position={[2.023, 0.866, -3.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items040.geometry}
        material={nodes.items040.material}
        position={[2.228, 0.913, -3.102]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items071.geometry}
        material={materials["Material.001"]}
        position={[2.156, 0.949, -3.467]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items052.geometry}
        material={nodes.items052.material}
        position={[1.89, 0.91, -3.474]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items076.geometry}
        material={materials["Material.004"]}
        position={[2.023, 0.866, -3.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items037.geometry}
        material={materials["Material.011"]}
        position={[0.027, 0.879, -3.477]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items041.geometry}
        material={nodes.items041.material}
        position={[1.565, 0.886, -3.553]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items008.geometry}
        material={nodes.items008.material}
        position={[1.664, 1.162, -3.642]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items009.geometry}
        material={nodes.items009.material}
        position={[1.648, 1.097, -3.559]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items010.geometry}
        material={nodes.items010.material}
        position={[1.625, 1.13, -3.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items011.geometry}
        material={nodes.items011.material}
        position={[1.592, 1.119, -3.646]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items042.geometry}
        material={materials["Material.009"]}
        position={[0.509, 1.141, -3.468]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items013.geometry}
        material={materials.wood_table_worn}
        position={[-1.976, 0.743, -2.717]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items015.geometry}
        material={materials["Material.006"]}
        position={[-1.985, 1.988, -2.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items053.geometry}
        material={materials["Material.005"]}
        position={[-1.987, 0.567, -2.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items016.geometry}
        material={materials.rusty_metal_02}
        position={[-2.3, 1.808, -2.618]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items017.geometry}
        material={materials.rusty_metal_02}
        position={[-2.3, 1.451, -2.618]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items054.geometry}
        material={materials["Material.013"]}
        position={[-2.155, 1.209, -2.869]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items019.geometry}
        material={materials["Material.001"]}
        position={[-2.112, 0.357, -2.921]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items038.geometry}
        material={materials.rusty_metal_02}
        position={[-2.177, 0.076, -2.837]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items057.geometry}
        material={materials["Material.008"]}
        position={[-2.107, 0.063, -2.461]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items058.geometry}
        material={materials["Material.014"]}
        position={[-2.174, 0.165, -2.587]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items059.geometry}
        material={materials["Material.010"]}
        position={[-2.078, 1.251, -2.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items063.geometry}
        material={materials["Material.009"]}
        position={[-2.097, 1.609, -2.842]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items067.geometry}
        material={nodes.items067.material}
        position={[-2.336, 0.804, -3.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items084.geometry}
        material={materials["Material.014"]}
        position={[-2.21, 1.124, -1.434]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items085.geometry}
        material={materials["Material.012"]}
        position={[-2.21, 1.291, -1.434]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items086.geometry}
        material={materials["Material.011"]}
        position={[-2.216, 1.454, -1.435]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items087.geometry}
        material={materials["Material.013"]}
        position={[-2.21, 1.209, -1.434]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items088.geometry}
        material={materials["Material.010"]}
        position={[-2.216, 1.536, -1.435]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items089.geometry}
        material={materials["Material.009"]}
        position={[-2.21, 1.823, -1.434]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items090.geometry}
        material={materials["Material.008"]}
        position={[-2.21, 1.905, -1.434]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items014.geometry}
        material={materials["Material.005"]}
        position={[-2.313, 0.514, -1.385]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items006.geometry}
        material={nodes.items006.material}
        position={[2.637, 2.471, -3.626]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items065.geometry}
        material={nodes.items065.material}
        position={[1.399, 1.981, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items066.geometry}
        material={nodes.items066.material}
        position={[0.772, 1.981, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items092.geometry}
        material={materials.wood_table_worn}
        position={[2.028, 0.055, -3.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items093.geometry}
        material={materials["Material.017"]}
        position={[2.656, 0.055, -3.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items094.geometry}
        material={nodes.items094.material}
        position={[1.087, 1.621, -3.426]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items097.geometry}
        material={nodes.items097.material}
        position={[1.401, 1.621, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items098.geometry}
        material={materials.wood_table_worn}
        position={[2.656, 1.621, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items100.geometry}
        material={nodes.items100.material}
        position={[0.773, 1.621, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items069.geometry}
        material={materials["Material.004"]}
        position={[-2.972, 0.95, 0.581]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items039.geometry}
        material={nodes.items039.material}
        position={[-2.393, 1.086, -1.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items060.geometry}
        material={materials["Material.001"]}
        position={[-2.078, 1.251, -2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items061.geometry}
        material={nodes.items061.material}
        position={[-2.227, 1.251, -2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items062.geometry}
        material={nodes.items062.material}
        position={[-2.227, 1.251, -2.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items051.geometry}
        material={materials["Material.015"]}
        position={[0.848, 0.889, -3.581]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items064.geometry}
        material={materials["Material.008"]}
        position={[-2.14, 1.609, -2.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items018.geometry}
        material={nodes.items018.material}
        position={[-2.3, 1.128, -2.618]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items102.geometry}
        material={materials["Material.002"]}
        position={[-1.985, 1.988, -2.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items103.geometry}
        material={materials["Material.002"]}
        position={[-1.987, 0.567, -2.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items104.geometry}
        material={nodes.items104.material}
      />
    </group>
  );
}

useGLTF.preload("models/newfixedmodel.glb");
