/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export  function ThirdModelBroke(props) {
  const { nodes, materials } = useGLTF("models/newbrokemodel.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall002.geometry}
        material={nodes.wall002.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall003.geometry}
        material={nodes.wall003.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall009.geometry}
        material={nodes.wall009.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall011.geometry}
        material={nodes.wall011.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall014.geometry}
        material={nodes.wall014.material}
        position={[1.087, 1.41, -3.626]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall018.geometry}
        material={materials.rusty_metal_02}
        position={[3.097, -0.081, -2.518]}
        rotation={[-0.036, -0.033, -0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall021.geometry}
        material={nodes.wall021.material}
        position={[-0.28, -0.692, 0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall027.geometry}
        material={nodes.wall027.material}
        position={[1.551, -1.135, -0.936]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall037.geometry}
        material={nodes.wall037.material}
        position={[3.196, -0.527, -1.849]}
        rotation={[-0.339, 0.132, 0.046]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall049_cell002.geometry}
        material={nodes.wall049_cell002.material}
        position={[-0.123, 0.021, -1.711]}
        rotation={[-0.01, 0.566, 0.018]}
        scale={1.726}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall049_cell003.geometry}
        material={materials.slab_tiles}
        position={[0.061, 0.012, -2.338]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall049_cell_cell001.geometry}
        material={nodes.wall049_cell_cell001.material}
        position={[1.774, 0.021, -2.14]}
        rotation={[-0.02, 0, 0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall049_cell_cell_cell.geometry}
        material={materials.slab_tiles}
        position={[-0.755, 0.015, -1.304]}
        rotation={[-0.006, 0, -0.018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["wall-please-work-what"].geometry}
        material={nodes["wall-please-work-what"].material}
        position={[-1.299, 0.996, -0.536]}
        scale={[0.927, 0.927, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall001_cell008_cell001.geometry}
        material={nodes.wall001_cell008_cell001.material}
        position={[-2.432, -0.247, 1.593]}
        scale={[0.892, 0.892, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall008_cell006.geometry}
        material={nodes.wall008_cell006.material}
        position={[2.138, -0.544, -1.738]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall001.geometry}
        material={nodes.wall001.material}
        position={[0.304, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall006.geometry}
        material={nodes.wall006.material}
        position={[-0.44, 0, 2.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items036.geometry}
        material={materials.slab_tiles}
        position={[1.396, 0.001, -2.103]}
        rotation={[0, 0.362, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items081.geometry}
        material={materials["Material.011"]}
        position={[2.668, 0.004, -3.298]}
        rotation={[0, 0.124, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items091.geometry}
        material={nodes.items091.material}
        position={[1.072, 0.889, -3.334]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items056.geometry}
        material={nodes.items056.material}
        position={[-0.638, 0, -0.182]}
        rotation={[0, 0.012, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items070.geometry}
        material={nodes.items070.material}
        position={[-1.449, 0.001, -0.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items002.geometry}
        material={materials["Material.013"]}
        position={[-1.285, 0.019, -0.182]}
        rotation={[0.053, -0.482, -1.543]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items003.geometry}
        material={nodes.items003.material}
        position={[-2.185, 0, 1.267]}
        rotation={[0, 0.294, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items004.geometry}
        material={nodes.items004.material}
        position={[-2.635, 1.298, 1.657]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items005.geometry}
        material={nodes.items005.material}
        position={[-2.432, 1.298, 1.657]}
        rotation={[-0.037, 0, -0.074]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items007.geometry}
        material={materials["Material.009"]}
        position={[-2.567, 0.694, 0.828]}
        rotation={[0, 0, -0.178]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items050.geometry}
        material={materials["Material.010"]}
        position={[-2.696, 0.835, 0.322]}
        rotation={[-0.167, 0.013, -0.319]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items074.geometry}
        material={nodes.items074.material}
        position={[-2.52, 0.697, 0.333]}
        rotation={[0, 0, -0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items075.geometry}
        material={materials.wood_table_worn}
        position={[-2.182, 0, 1.266]}
        rotation={[0, 0.294, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items082.geometry}
        material={nodes.items082.material}
        position={[-2.361, 0.669, 0.321]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items083.geometry}
        material={materials.wood_table_worn}
        position={[-2.801, 1.423, 1.145]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items072.geometry}
        material={materials["Material.002"]}
        position={[0.215, 0.172, -1.96]}
        rotation={[0.005, 0.028, -1.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items073.geometry}
        material={nodes.items073.material}
        position={[0.554, 0.137, -1.594]}
        rotation={[-Math.PI / 2, 0, 0.697]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items001.geometry}
        material={materials["Material.005"]}
        position={[0.431, 0.173, -1.827]}
        rotation={[-Math.PI / 2, 0, 0.697]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items012.geometry}
        material={nodes.items012.material}
        position={[2.023, 0.866, -3.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items040.geometry}
        material={nodes.items040.material}
        position={[2.228, 0.913, -3.102]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items071.geometry}
        material={materials["Material.006"]}
        position={[1.775, 0.018, -2.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items052.geometry}
        material={nodes.items052.material}
        position={[1.89, 0.91, -3.474]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items076.geometry}
        material={materials.slab_tiles}
        position={[2.023, 0.866, -3.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items037.geometry}
        material={materials["Material.007"]}
        position={[-0.173, 0.879, -3.344]}
        rotation={[0, 0.507, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items041.geometry}
        material={nodes.items041.material}
        position={[1.606, 0.918, -3.318]}
        rotation={[-3.068, 1.491, -1.69]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items008.geometry}
        material={nodes.items008.material}
        position={[0.924, 0.848, -3.532]}
        rotation={[-0.814, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items009.geometry}
        material={nodes.items009.material}
        position={[0.999, 0.797, -3.485]}
        rotation={[-0.265, 1.08, -0.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items010.geometry}
        material={nodes.items010.material}
        position={[0.885, 0.922, -3.419]}
        rotation={[-0.814, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items011.geometry}
        material={nodes.items011.material}
        position={[0.852, 0.816, -3.505]}
        rotation={[-0.814, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items042.geometry}
        material={materials["Material.005"]}
        position={[0.349, 0.952, -3.383]}
        rotation={[-Math.PI, 1.283, -1.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items013.geometry}
        material={nodes.items013.material}
        position={[-1.976, 0.743, -2.717]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items015.geometry}
        material={materials["Material.016"]}
        position={[-1.833, 1.988, -2.233]}
        rotation={[0, 0.046, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items053.geometry}
        material={materials["Material.015"]}
        position={[-1.939, 0.567, -2.013]}
        rotation={[0, 0.014, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items016.geometry}
        material={materials.rusty_metal_02}
        position={[-2.219, 1.779, -2.615]}
        rotation={[0.02, -0.019, -0.046]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items017.geometry}
        material={materials.wood_table_worn}
        position={[-2.24, 1.457, -2.713]}
        rotation={[0, -0.485, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items054.geometry}
        material={nodes.items054.material}
        position={[-1.618, 0.114, -2.546]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items019.geometry}
        material={materials["Material.013"]}
        position={[-2.112, 0.357, -2.921]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items038.geometry}
        material={materials.rusty_metal_02}
        position={[-0.419, 0.026, 1.287]}
        rotation={[0, -0.696, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items057.geometry}
        material={materials["Material.006"]}
        position={[-2.107, 0.063, -2.461]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items058.geometry}
        material={nodes.items058.material}
        position={[-2.174, 0.165, -2.587]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items059.geometry}
        material={materials["Material.003"]}
        position={[-2.078, 1.251, -2.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items063.geometry}
        material={nodes.items063.material}
        position={[-2.042, 1.564, -2.854]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items067.geometry}
        material={materials["Material.008"]}
        position={[-0.61, 0.751, -2.617]}
        rotation={[-1.44, 1.358, 1.432]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items084.geometry}
        material={materials["Material.007"]}
        position={[-0.869, -0.002, -0.93]}
        rotation={[0, 0.227, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items085.geometry}
        material={materials["Material.004"]}
        position={[-2.21, 1.124, -1.434]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items086.geometry}
        material={materials["Material.003"]}
        position={[-2.216, 1.428, -1.445]}
        rotation={[1.991, 1.449, -1.989]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items087.geometry}
        material={materials["Material.003"]}
        position={[-0.416, 0.014, -2.284]}
        rotation={[0, -0.921, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items088.geometry}
        material={materials["Material.006"]}
        position={[-1.649, 0.03, 0.425]}
        rotation={[-3.125, 0.19, -3.087]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items089.geometry}
        material={materials["Material.002"]}
        position={[-2.21, 1.823, -1.434]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items090.geometry}
        material={materials["Material.005"]}
        position={[-1.119, 0.017, 1.058]}
        rotation={[0, 0.202, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items014.geometry}
        material={materials["Material.014"]}
        position={[-2.313, 0.514, -1.385]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items006.geometry}
        material={nodes.items006.material}
        position={[2.637, 2.471, -3.626]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items065.geometry}
        material={nodes.items065.material}
        position={[1.399, 1.981, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items066.geometry}
        material={nodes.items066.material}
        position={[0.772, 1.981, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items092.geometry}
        material={materials.wood_table_worn}
        position={[2.028, 0.055, -3.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items093.geometry}
        material={nodes.items093.material}
        position={[2.656, 0.055, -3.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items094.geometry}
        material={nodes.items094.material}
        position={[1.087, 1.621, -3.426]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items097.geometry}
        material={nodes.items097.material}
        position={[1.401, 1.621, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items100.geometry}
        material={nodes.items100.material}
        position={[0.773, 1.621, -3.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items039.geometry}
        material={nodes.items039.material}
        position={[-2.393, 1.086, -1.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items060.geometry}
        material={materials["Material.002"]}
        position={[-2.078, 1.251, -2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items061.geometry}
        material={nodes.items061.material}
        position={[-2.227, 1.251, -2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items062.geometry}
        material={nodes.items062.material}
        position={[-2.227, 1.251, -2.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items051.geometry}
        material={materials["Material.010"]}
        position={[0.848, 0.889, -3.581]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items064.geometry}
        material={nodes.items064.material}
        position={[-2.388, 1.76, -2.771]}
        rotation={[0, 0, -1.582]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items018.geometry}
        material={materials.wood_table_worn}
        position={[-2.3, 1.128, -2.618]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items102.geometry}
        material={materials["Material.001"]}
        position={[-1.833, 1.988, -2.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items103.geometry}
        material={materials["Material.001"]}
        position={[-1.987, 0.567, -2.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items104.geometry}
        material={nodes.items104.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.items020.geometry}
        material={materials.rusty_metal_02}
        position={[-1.511, 0.044, -1.86]}
        rotation={[0, 0.104, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/newbrokemodel.glb");
