/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function ThirdCharacterHappy(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "models/MaintenanceClean-proc-meshopt-m.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        if (action && action.play) {
          action.play();
        }
      });
    }
  }, []);
  return (
    <group ref={group} position={[2 , 0 , -3.0]} {...props} dispose={null}>
      <group name="Scene">
        <group name="MaintenanceCleanglb">
          <group
            name="Ch1_CTRL00"
            position={[-0.754, 0.014, 0.991]}
            rotation={[0, 1.126, 0]}
            scale={1.358}
          >
            <skinnedMesh
              name="Object086"
              geometry={nodes.Object086.geometry}
              material={nodes.Object086.material}
              skeleton={nodes.Object086.skeleton}
              position={[0.061, 0.657, 0.102]}
            />
          </group>
          <primitive object={nodes.Point276} />
          <skinnedMesh
            name="Object126"
            geometry={nodes.Object126.geometry}
            material={nodes.Object126.material}
            skeleton={nodes.Object126.skeleton}
            position={[-0.593, 0.906, 0.975]}
            rotation={[0, 1.126, 0]}
            scale={1.358}
          />
          <skinnedMesh
            name="Object127"
            geometry={nodes.Object127.geometry}
            material={nodes.Object127.material}
            skeleton={nodes.Object127.skeleton}
            position={[-0.593, 0.906, 0.975]}
            rotation={[0, 1.126, 0]}
            scale={1.358}
          />
          <skinnedMesh
            name="Object128"
            geometry={nodes.Object128.geometry}
            material={nodes.Object128.material}
            skeleton={nodes.Object128.skeleton}
            position={[-0.593, 0.906, 0.975]}
            rotation={[0, 1.126, 0]}
            scale={1.358}
          />
          <skinnedMesh
            name="Object129"
            geometry={nodes.Object129.geometry}
            material={nodes.Object129.material}
            skeleton={nodes.Object129.skeleton}
            position={[-0.593, 0.906, 0.975]}
            rotation={[0, 1.126, 0]}
            scale={1.358}
          />
          <skinnedMesh
            name="Object130"
            geometry={nodes.Object130.geometry}
            material={nodes.Object130.material}
            skeleton={nodes.Object130.skeleton}
            position={[-0.593, 0.906, 0.975]}
            rotation={[0, 1.126, 0]}
            scale={1.358}
          />
          <skinnedMesh
            name="Object131"
            geometry={nodes.Object131.geometry}
            material={nodes.Object131.material}
            skeleton={nodes.Object131.skeleton}
            position={[-0.593, 0.906, 0.975]}
            rotation={[0, 1.126, 0]}
            scale={1.358}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/MaintenanceClean-proc-meshopt-m.glb");
